Repository rajdeepchakraborty-rc/School-Carnival-2K24, pull requests merged in 2024-12, with the labels that each got.

#9 add popup section
  closer.jpg
  index.css
  index.html
  popup_image.jpg
Labels: feature

#11 add home page
  Assets/Q_code.jpg
  Assets/bakground_image.jpg
  index.css
  index.html
Labels: feature

#15 Minor Changes and Footer section Revamp
  Assets/Favicon.png
  index.css
  index.html
Labels: enhancement, feature

#20 Added Activities for the Event and Resolved minor Responsive Bugs
  index.css
  index.html
Labels: bug, enhancement, feature

#23 fixed title
  index.css
  index.html
  responsive.css
Labels: bug

#25 fixed responsive game section
  index.css
  responsive.css
Labels: bug, responsive

#34 Updated Details in footer, Added Event Rules & Registration form
  Assets/Rules_SchoolCarnival2024.pdf
  index.css
  index.html
Labels: bug, enhancement

#35 Added the Event-Specific details on the Card back
  index.html
Labels: enhancement, feature

#37 Updated: Contact Details on Card back
  index.html
Labels: enhancement

#39 add rules in game section
  index.css
  index.html
  responsive.css
Labels: feature

#41 Updated Games section and Fixed bugs
  index.css
  index.html
Labels: bug, enhancement

#43 Added About Section
  index.css
  index.html
Labels: feature

#42 Added Team Section
  Assets/Pritam Tung.jpg
  Assets/Rajdeep Chakraborty.jpg
  index.css
  index.html
Labels: feature

#46 Added: Website PreLoader
  index.css
  index.html
Labels: enhancement, feature

#49 Team section responsivess for mobile devices
  responsive.css
Labels: responsive

#50 add responsive
  Responsive_T.css
Labels: bug, responsive

#53 Added: New Rules PDF file
  Assets/Rules_SchoolCarnival2024.pdf
Labels: bug, documentation
